### ISSUE TITLE
Crash serwera z 22.01.2024 16:00

### ISSUE THREAD

**Issue by Mrucznik** [MrucznikRolePlay/Mrucznik-RP-gamemode#365]
Logi:
[log-core] fatal signal '2' (SIGINT) catched

terminate called after throwing an instance of 'fmt::FormatError'
  what():  unmatched '}' in format string

crashdetect:
[20/01/2024 16:01:02] Server crashed while executing Mrucznik-RP.amx
[22/01/2024 16:00:30] Server crashed while executing Mrucznik-RP.amx

**Comment by xselectx** [comment]
Opisy i formatowanie koloru może?

**Comment by Mrucznik** [comment]
blad wiecej nie zauwazony wiec zamykam
