### ISSUE TITLE
Bug z cooldownem zdrapek

### ISSUE THREAD

**Issue by gumbalowsky** [MrucznikRolePlay/Mrucznik-RP-gamemode#390]
Dając /q można zresetować sobie timer na zdrapki, omijając godziny cooldown.

**Comment by EvansMRP** [comment]
Chyba poprawione

**Comment by Niceboy-Dev** [comment]
Błąd nadal występuje. Po relogu cooldown się resetuje.

**Comment by Mrucznik** [comment]
poprawione
