### ISSUE TITLE
Spadki FPS generuja ogromne koszty na Taxi

### ISSUE THREAD

**Issue by Allerek** [MrucznikRolePlay/Mrucznik-RP-gamemode#397]
Chwila przed spadkiem fps do '1'(cheater)
![image](https://github.com/Mrucznik/Mrucznik-RP-2.5/assets/12304071/0bc65c5e-f48a-4043-a85e-aded04113498)
Po zakończeniu spadków - kilka metrów dalej
![image](https://github.com/Mrucznik/Mrucznik-RP-2.5/assets/12304071/e4b418ed-5d9f-4051-bd3d-9ae3c2ea1dc5)

Koszt jest realny i na koniec zostajemy z długiem.

**Comment by EvansMRP** [comment]
Chyba po zmianie hostingu na MGHost problem ustąpił.

**Comment by gumbalowsky** [comment]
#443 
Spowodowane teleportacją auta na duże dystanse, serwer przetworzył pakiety teleportacji auta z graczami w środku ale klient kierowcy "zniwelował" teleport i w taki sposób się nabiła kasa.
Najlepiej byłoby dodać limit maksymalnej kwoty, jaka może zostać dodana podczas np. jednej sekundy jazdy

**Comment by Mrucznik** [comment]
poprawione
