### ISSUE TITLE
KT - Kierowca nie otrzymuje profitu z /fare

### ISSUE THREAD

**Issue by EvansMRP** [MrucznikRolePlay/Mrucznik-RP-gamemode#443]
Kierowca korporacji transportowej nie dostaje żadnych profitów z wykonanego przejazdu(/fare), wszystko prawdopodobnie idzie do sejfu frakcyjnego nic na saldo gracza.

Aktualne ceny możliwe do ustawienia 200$ - 2000$

**Comment by EvansMRP** [comment]
Dodatkowo można to oszukać przez teleportowanie się z graczem siedzącym na G
![obraz](https://github.com/MrucznikRolePlay/Mrucznik-RP-gamemode/assets/38770962/74ea63cb-a5b2-435e-be3a-cdc1d0892d41)

**Comment by EvansMRP** [comment]
Proszę również o weryfikacje CMD /lot prawdopodobnie też nie działa jak powinna.

**Comment by gumbalowsky** [comment]
`Taxi_Pay();` do edycji kasy która idzie do sejfu,
TransportDist do poprawy poprzez metodę z #397 dla 2. problemu
![obraz](https://github.com/MrucznikRolePlay/Mrucznik-RP-gamemode/assets/24590213/68cb67f0-a400-4d53-a5af-13316e1849c5)

**Comment by Mrucznik** [comment]
poprawione
